### ISSUE TITLE
Issues while installing - REg

### ISSUE THREAD

**Issue by karuppucs** [validatedpatterns/retail#6]
Hi Team,

I am trying to install the retail application on my openshift cluster and its trying to get the postgres_util image from repository which doesn't exist. Can you please help me to setup the application in my openshift cluster with proper steps?

Thank you.
REgards,
Karuppusamy M

**Comment by mhjacks** [comment]
Hello - sorry for not seeing this earlier; there were a number of problems with the retail pattern as it existed when you last tried it. Would you mind giving it a try again? It should work a lot better now. (I don't know that I ever saw the issue with postgres_util, but if there's a problem there I will look into it.)

Thanks!
